apiVersion: backup.devops.lab/v1
kind: EtcdBackup
metadata:
  labels:
    app.kubernetes.io/name: etcd-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: etcdbackup-sample
spec:
  # TODO(user): Add fields here
